### ISSUE TITLE
A previous public call from the list of matched calls does not display

### ISSUE THREAD

**Issue by svatek** [opendatacz/pc-filing-app#32]
Probably related to #31. When a found past call (matching the current private call) is clicked upon, a progress bar just appears and stays forever. 
On the console, for the request such as "http://lod2.vse.cz:8080/pc-filing-app/PCFilingApp?action=getContractJson&copyContractURL=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fvestnikverejnychzakazek.cz%2Fpublic-contract%2F212679-7202011012679%2Flot%2F1"
an "HTTP/1.1 500 Internal Server Error" is returned.

**Comment by jindrichmynarz** [comment]
This is the same issue as #28, which was resolved a couple of days ago in the development branch, but haven't been merged into the master and deployed to lod2.vse.cz. Now I've merged that fix into the master and deployed it to lod2.vse.cz, but surprisingly it doesn't work there. It might be a Tomcat-specific error.

**Comment by jindrichmynarz** [comment]
OK, so this wasn't a Tomcat-specific error, but an issue of an older version being cached. Now it works in lod2.vse.cz as well. Please verify if it works for you and if so, close the issue.

**Comment by svatek** [comment]
Unfortunately, the problem persists, with same kind of error. (Now tried for a call matching an already published call, but this probably should not matter? Could try for a private one if needed.)

**Comment by jindrichmynarz** [comment]
This is likely the same issue that I originally have, which is a browser holding on outdated assets for far too long. Try refreshing the app couple of times or even directly flush the browser's cache.

For me it works for both private and public contracts.

**Comment by jindrichmynarz** [comment]
This issue has been resolved, but it may still occur in browsers that keep the previous version cached.

**Comment by svatek** [comment]
Reopening.
Opening a _certain_ similar contract from the list fails again.
This means, calling http://lod2.vse.cz:8080/pc-filing-app/buyer-view-event.jsp from http://lod2.vse.cz:8080/pc-filing-app/buyer-similar-events.jsp?private=true#page=2.
The progress bar freezes, and the console lists "TypeError: data.criteria is undefined"

Specifically, this occurs for the call (now published) "Hypotetická zakázka ČHMÚ - fragment" (), similar contract no. 20, "Provádění odběrů a rozborů vzorků monitoringu jakosti povrchových vod a sedimentů - Oblast povodí Labe ".
